application: wterminal
version: 1
runtime: python
api_version: 1

handlers:
- url: /css
  static_dir: stylesheets

- url: /js
  static_dir: js

- url: /downloads
  static_dir: downloads

- url: /.*
  script: index.py
